package lexer;

public enum TokenType {
    KEYWORD_BUILD_TRIANGLE,
    KEYWORD_BUILD_HEIGHT,
    KEYWORD_BUILD_MEDIAN,
    KEYWORD_BUILD_BISECTOR,
    KEYWORD_ISOSCELES,
    KEYWORD_RIGHT,
    POINT,
    DEF_IDENTIFIER,
    UKRAINIAN_IDENTIFIER,
    IDENTIFIER,
    INTEGER,
    FLOAT,
    SINGLE_LINE_COMMENT,
    MULTI_LINE_COMMENT,
    OPERATOR,
    BRACKET,
    HASH,
    SEMICOLON,
    ERROR
}
